
create table if not exists public.email_scraper_node (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  url text not null,
  client_tag text not null,
  status text null,
  facebook_urls text[] null,
  emails text[] null,
  message text null,
  retry_count integer not null default 0,
  updated_at timestamp with time zone not null default now(),
  scrape_type text not null default 'http_request',
  needs_browser_rendering boolean not null default false,
  processed boolean not null default false,
  constraint email_scraper_node_pkey primary key (id)
) TABLESPACE pg_default;

-- Trigger Function
CREATE OR REPLACE FUNCTION set_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger
DROP TRIGGER IF EXISTS trg_email_scraper_node_updated_at ON public.email_scraper_node;
CREATE TRIGGER trg_email_scraper_node_updated_at
BEFORE UPDATE ON email_scraper_node
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

-- Indexes for performance
CREATE INDEX IF NOT EXISTS idx_email_scraper_node_status_scrape_type 
ON public.email_scraper_node (status, scrape_type, created_at) 
WHERE status = 'need_browser_rendering' ;

-- RPC Function for worker (only processes http_request scrape_type)
CREATE OR REPLACE FUNCTION get_next_email_scraper_nodes_need_browser_rendering(batch_size INT)
RETURNS SETOF public.email_scraper_node AS $$
BEGIN
  RETURN QUERY
  UPDATE public.email_scraper_node
  SET status = 'processing', updated_at = NOW()
  WHERE id IN (
    SELECT id
    FROM public.email_scraper_node
    WHERE status = 'need_browser_rendering'
    ORDER BY created_at ASC
    LIMIT batch_size
    FOR UPDATE SKIP LOCKED
  )
  RETURNING *;
END;
$$ LANGUAGE plpgsql;

