-- Supabase schema for email_google_search table

CREATE TABLE public."email-google-search" (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    email_scraper_id bigint NULL,
    results text[] NULL,
    status text NULL DEFAULT 'queued',
    url text NULL,
    client_tag text NULL,
    emails text[] NULL
);

-- Index for faster queued status lookups
CREATE INDEX idx_email_google_search_status ON public."email-google-search"(status);

-- Index for client_tag filtering
CREATE INDEX idx_email_google_search_client_tag ON public."email-google-search"(client_tag);
